#!/bin/sh
export ROOT=`dirname $0`
java                                 \
     -Djava.library.path="$ROOT/lib" \
     -Dscala.usejavacp=true          \
     -cp "$ROOT/bin":`find "$ROOT" "$1" -name "*.jar" | xargs | sed "s/ /:/g"` \
     -d64 -Xmx2g -server\
     com.km.sing.Server "$@"